[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14"
  CI = "false"

[[redirects]]
  from = "/venturosa/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://seu-backend.vercel.app"
  CI = "false"
